config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show] do
    resources :todos, only: [:new, :create, :destroy]
  end

  root to: "welcome#index"

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to user_path(current_user), alert: "That is not the page you are looking for"
  end

  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  # Render 404 page when record not found
  def render_404      
     render file: "public/404.html", status: 404
  end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.find(params[:user_id])
    @todo = Todo.new
    authorize @todo
  end

  def create
    @user = User.find(params[:user_id])
    @todo = current_user.todos.build(todo_params)
    authorize @todo
    if @todo.save
      redirect_to @user, notice: 'Your new To-Do was saved'
    else
      redirect_to @user, alert: 'There was an error saving your To-Do'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @todo = Todo.find(params[:id])
    authorize @todo
    if @todo.destroy
      redirect_to @user, notice: 'Your To-Do was deleted'
    else
      redirect_to @user, alert: 'There was an error deleting your To-Do'
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @todo = Todo.new
    @todos = @user.todos
    authorize @user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blocitoff
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-pills
        %li
          =link_to 'Blocitoff', root_path
        %li
          -if current_user
            = link_to 'Home', user_path(current_user)
        .pull-right.sign-options
          -if current_user
            = link_to 'Account', edit_user_registration_path
            |
            = link_to 'Sign Out', destroy_user_session_path, method: :delete
          -else
            = link_to 'Sign Up', new_user_registration_path
            or 
            \#{link_to 'Sign In', new_user_session_path}
            
      -if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = flash[:notice]
      -if flash[:alert]
        .alert.alert-danger
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = flash[:alert]

      = yield

app/views/todos/_new.html.haml
= form_for [@user, @todo] do |f|
  = f.text_field :description, placeholder: 'Description'
  = f.submit 'Save'

app/views/todos/new.html.haml
%br/
.row
  .col-md-4
    %h3 New To-Do
    = form_for [@user, @todo] do |f|
      .form-group
        = f.text_field :description, class: 'form-control', placeholder: 'Description'
        %br/
        = f.submit 'Save', class: 'btn btn-success'

app/views/users/show.html.haml
%br/
%table.table.table-striped.table-bordered
  %tr
    %th Todos
    %th Time Left
    %th Completed?
  - @todos.each do |t|
    %tr
      %td= t.description
      %td= distance_of_time_in_words(Date.today, t.created_at.to_date + 7.days)
      %td= link_to 'Delete', user_todo_path(@user, t), method: :delete
%p= link_to 'New To-do', new_user_todo_path(@user, @todo)

app/views/welcome/index.html.haml
%br/
.container
  .jumbotron
    %h1 Hey, Blocitoff!
    %h3 A To-Do app to keep you organized and timely.
    %p
      %strong Blocitoff
      gives you the power of making to-dos while keeping the clutter low.  After a week, old to-dos are deleted, because they apparently weren't worthy of your time.
    =link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary'
    or
    \#{link_to 'Sign In', new_user_session_path, class: 'btn btn-primary'}
    %p
    %small Blocitoff is responsible for any feelings of being a productive superhero, fighter of procrastination, champion of the less organized, and all-around bamf.